spring:
  profiles:
    active: dev
  config:
    name: dev
  datasource:
    url: jdbc:mysql://localhost:3306/workout
    password: root
    username: toor
    driver-class-name: com.mysql.cj.jdbc.Driver
